Failure # 1 (occurred at 2020-08-17_21-50-05)
Traceback (most recent call last):
  File "/home/trentonbricken/.local/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 468, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/trentonbricken/.local/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 430, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/trentonbricken/.local/lib/python3.7/site-packages/ray/worker.py", line 1474, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): [36mray::ImplicitFunc.train()[39m (pid=64369, ip=10.142.0.3)
  File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 400, in ray._raylet.execute_task.function_executor
  File "/home/trentonbricken/.local/lib/python3.7/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/home/trentonbricken/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 217, in _train
    self._report_thread_runner_error(block=True)
  File "/home/trentonbricken/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 262, in _report_thread_runner_error
    .format(err_tb_str)))
ray.tune.error.TuneError: Trial raised an exception. Traceback:
[36mray::ImplicitFunc.train()[39m (pid=64369, ip=10.142.0.3)
  File "/home/trentonbricken/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 109, in run
    self._entrypoint()
  File "/home/trentonbricken/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 163, in entrypoint
    return self._trainable_func(config, self._status_reporter)
  File "/home/trentonbricken/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 273, in _trainable_func
    output = train_func(config)
  File "trainer.py", line 227, in run_lightning
    model = LightningTemplate(game_dir, config, train_buffer, test_buffer)
  File "/home/trentonbricken/fem/lightning_trainer.py", line 64, in __init__
    self.hparams['hidden_sizes'])
  File "/home/trentonbricken/fem/models/upsd_model.py", line 79, in __init__
    self.desires_layers.append( nn.Linear(desires_size, hidden_sizes[j+1]) )
  File "/home/trentonbricken/.local/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 77, in __init__
    self.reset_parameters()
  File "/home/trentonbricken/.local/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 80, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/home/trentonbricken/.local/lib/python3.7/site-packages/torch/nn/init.py", line 312, in kaiming_uniform_
    std = gain / math.sqrt(fan)
ZeroDivisionError: float division by zero

